### ISSUE TITLE
Support git annex

### ISSUE THREAD

**Issue by fire** [SRombauts/UE4GitPlugin#1] opened 2014-05-22 16:42 UTC
Please look into support for git annex.

**Comment by saim80** [comment] 2015-02-17 06:59
I just want to leave a note regarding this feature.
I tried both git-annex and git-media to see how they are get along with Unreal Editor. 

git-annex creates a lot of symlinks. This resulted in crash when opening UE4 project after setting up git-annex. My best guess is that UE4 is not really resolving symlink when they access files. 

So far, git-media works without making UE4 editor crash. The only downside I found is that, once 'uasset', 'umap' files are added into the project, they aren't really tracked by standard git index. I always had to check media type status with 'git media sync' command. Note that I just tried local disk sync'ing, nothing else, e.g.,. Amazon S3, etc.

Hope this helps.

**Comment by SRombauts** [comment] 2015-02-17 07:04
Hi, thank you for your feedback!

**Comment by fire** [comment] 2015-02-17 16:34
On Windows, git-annex creates direct files as far as I know. Are you testing on Linux?

**Comment by saim80** [comment] 2015-02-17 16:42
@fire I'm using a Mac. I think that git-annex works this way for all unix-variant, e.g., linux, BSD, mac, etc.

**Comment by fire** [comment] 2015-02-22 21:42
I will bring this to the attention of Epic games. Perhaps the problem with not resolving symlinks will be resolved in future release of UE4.

**Comment by fire** [comment] 2015-02-22 23:20
@saim80 Can you create a stacktrace or a callstack?

**Comment by saim80** [comment] 2015-03-03 04:34
@fire Here's a screenshot of the crash. I could reproduce the issue from 4.7.1.

http://d.pr/i/11ZCc

Reproduce Step:
- Create sample project. I chose top down c++ project.
- Once project initialization finishes, open terminal
- $ git init
- $ git annex init
- $ git annex add ${PATH_TO_ANY_CONTENT}, e.g., ./Content/Character/HeroTPP.uasset
- Go back to UE4 editor.
- In Content Browser, try to re-open/open the asset that is added to git annex.

**Comment by saim80** [comment] 2015-04-18 05:20
@fire  I happened to come across this git annex documentation. So, I think this page explains why things didn't crash on Windows. http://git-annex.branchable.com/direct_mode/ I assume using direct mode in Mac environment also will resolve issues with Unreal Editor. I haven't tried because I decided to use Windows for Unreal.

**Comment by SRombauts** [comment] 2016-02-15 21:16
Just wanting to report here that Github "LFS" is working flawlessly under Windows :)

**Closed by SRombauts** 2016-02-15 21:16 UTC
Labels: enhancement
